# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install: gem upgrade CocoaPods && cd Example && pod install && cd -
script:
- xctool test -workspace Example/OLOverlay.xcworkspace -scheme OLOverlay -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
